# Generated by Django 4.1 on 2022-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='flashcards',
            field=models.ManyToManyField(to='main_app.flashcard'),
        ),
    ]
